### ISSUE TITLE
Multi-press button functionality

### ISSUE THREAD

**Issue by mjkosin68** [jay-kub/inovelli-matter-switch-tap-sequences#10]
The blueprint is not allowing me to use multi-press of any of the buttons.  I am trying to use double-press as a trigger, and is only responding to single press actions.

**Comment by jay-kub** [comment]
Another user reported a similar issue which I think might be an HA bug. After a multi-press, can you pull up the Changed Variables from the Trace log of the automation? There will be a list of "event_types:" which should consist of multi_press_1, multi_press_2, etc.. If instead you see "initial_press, short_release, etc." this is the potential HA bug. If so, would you mind opening an issue on the HA Discord in the #related-tech channel?

**Comment by mjkosin68** [comment]
Seems to be tracking correctly...

 to_state:
    entity_id: event.white_series_smart_2_1_switch_up
    state: '2024-12-07T19:11:19.310+00:00'
    attributes:
      event_types:
        - multi_press_1
        - multi_press_2
        - multi_press_3
        - multi_press_4
        - multi_press_5
        - long_press
        - long_release
      event_type: multi_press_3
      previousPosition: 1
      totalNumberOfPressesCounted: 3
      device_class: button
      friendly_name: White Series Smart 2-1 Switch Up
    last_changed: '2024-12-07T19:11:19.310441+00:00'
    last_reported: '2024-12-07T19:11:19.310441+00:00'
    last_updated: '2024-12-07T19:11:19.310441+00:00'
    context:
      id: 01JEH8H48EG66Y8N6TB3FEA3CQ
      parent_id: null
      user_id: null

**Comment by mjkosin68** [comment]
That was a triple-press btw

**Comment by jay-kub** [comment]
When you pull up the trace there should be a visual representation of the path it took--not sure what to call it--but can you screenshot that and share it here along with the automation yaml?

**Comment by mjkosin68** [comment]
See attached...
![Trace (errors)](https://github.com/user-attachments/assets/633e9bec-a693-47f3-aab0-36caeb057a4d)
![Trace (full)](https://github.com/user-attachments/assets/755be216-8c62-4b14-bbbd-d1d7050e7634)
[Inovelli yaml.txt](https://github.com/user-attachments/files/18053753/Inovelli.yaml.txt)

**Comment by jay-kub** [comment]
Looks like the action for up2 is erroring out:

<img width="187" alt="image" src="https://github.com/user-attachments/assets/5a866eff-3b00-4a9d-bccf-16ecb160f810">

In your automation yaml file try changing up2 to the following:

```yaml
    up2:
      - action: light.turn_on
        target:
          entity_id: light.test_rgb
        data:
          brightness_pct: 95
          rgbww_color:
            - 0
            - 0
            - 0
            - 256
            - 0
```

**Comment by mjkosin68** [comment]
Perfect, but I screwed up, the max value is 255, not 256.  Once I changed that, it works great!!

Thanks
