### ISSUE TITLE
Please add ability to bind to a light group

### ISSUE THREAD

**Issue by philnewmangit** [jay-kub/inovelli-matter-switch-tap-sequences#5]
I have a room with an Inovelli and 3 smart bulbs. I have a light group helper set up to control the lights as one. I would like to either be able to:
1. Bind the switch to all 3 bulbs
2. Bind the switch to the light group
Great blueprint. Looking forward to see these improvements.

**Comment by jay-kub** [comment]
Thanks for the kind words!

The Light Binding section is at the bottom of the blueprint and you can enter your light group entity in the Target Light field. Have you tried that yet? If so, let me know what issues you're running into.

**Comment by philnewmangit** [comment]
Thanks for the quick response. I was looking at the field for the switch
light LED and not the entity to bind it to. Got it working now!

Phil
