### ISSUE TITLE
Odd light behavior with variable HA light levels

### ISSUE THREAD

**Issue by Coder84619** [jay-kub/inovelli-matter-switch-tap-sequences#7]
I use Blacky's sensor light blueprint to control the brightness level of my lights. His blueprint is highly configurable and supports dynamic lighting based on various factors. If I have Hue lights in 'smart switch mode' for the Inovelli switch with this tap sequence BP, I get odd light level behavior.

Specifically, I've enabled "brightness sync" and "reverse sync" on the switch blueprint. I then configured the minimum brightness, for example, to 5 percent. When Blacky's sensor script detects motion in my closet the lights are briefly at the sensor's light desired level, then a split second later reset to the level as set in the Inovelli BP. 

If I disable 'brightness sync' this behavior does NOT happen, then it appears I can't use the white switch paddles to vary the Hue lights dimming level. I need both sync options enabled for full functionality, but that results in lighting level mismatch. 

I would propose to change the automation code (or add an option) to ignore the minimum brightness level if the light is turned on programmatically by HA. I only want the minimum brightness level to be triggered with a human presses the up paddle. The sensor light BP can then set the light dimming level as needed without being changed by this BP.

**Comment by jay-kub** [comment]
It sounds like your Blacky sensor light blueprint is configured to control your hue lights directly. If you change it to control the Inovelli Switch Light, does that solve your issue?

Ideally all blueprints, scripts, dashboards, etc. should point to the Inovelli Switch, which will then sync to your target light. It's also best if you don't expose the target light to HA voice assistants, and then update the aliases for the Inovelli Switch Light to match the name of the target light. That way when you say something like "OK Google, turn on the closet hue to 50% brightness" it will turn the Inovelli Switch to 50%, then my blueprint will turn on your closet hue to 50%, and everything stays in sync.

**Comment by Coder84619** [comment]
I don't think pointing Blacky's blueprint to the switch will work for me:

1) Doesn't look like I can control the color temp of the Hue light, which is critical
2) I also use scenes extensively which set color temp directly via the Hue entities

Am I missing something?

**Comment by jay-kub** [comment]
You could point Blacky's BP to both lights.
